# These tests were generated by Claude and improved slightly.
# More work and thought is needed, but this is better than nothing.

using Test
using ReproducibleJobs
using ReproducibleJobs: create_spec, with_scheduler, Preprocessing, ProcessingException, cached


# All test functions must be at module scope (named, non-closure) so the
# scheduler can hash them reliably.

const _CALLS = Dict{Symbol,Int}()
_N(s::Symbol) = get(_CALLS, s, 0)           # read count
_C(s::Symbol) = (_CALLS[s] = _N(s) + 1)    # increment count

# Shared compute primitives (no counting)
my_double(x; __version=v"1.0.0") = 2x
my_add(a, b; __version=v"1.0.0") = a + b
my_val(x; __version=v"1.0.0") = x

# Test 1
t1_f(x; __version=v"1.0.0") = (_C(:t1_f); 2x)

# Test 2 — single preprocessing step
t2_double(x; __version=v"1.0.0")       = (_C(:t2_double); 2x)
t2_step1(::Preprocessing, x_job)       = (_C(:t2_step1); create_spec(t2_double, x_job; __version=v"1.0.0"))

# Test 3 — two-level preprocessing
t3_inner(::Preprocessing, x_job) = (_C(:t3_inner); create_spec(my_double, x_job; __version=v"1.0.0"))
t3_outer(::Preprocessing, x_job) = (_C(:t3_outer); create_spec(Preprocess(t3_inner), x_job))

# Test 4 — prefetched dep in preprocessing output
t4_get_len(x; __version=v"1.0.0") = (_C(:t4_get_len); length(x))
t4_use_len(n; __version=v"1.0.0") = (_C(:t4_use_len); n * 10)
function t4_make_len_spec(::Preprocessing, data_job)
	len_spec = create_spec(t4_get_len, data_job; __version=v"1.0.0")
	create_spec(t4_use_len, prefetched(len_spec); __version=v"1.0.0")
end

# Test 5 — should_forward_child: preprocessing dep of normal spec
t5_double(x; __version=v"1.0.0")    = (_C(:t5_double); 2x)
t5_preproc(::Preprocessing, x_job)  = (_C(:t5_preproc); create_spec(t5_double, x_job; __version=v"1.0.0"))

# Test 6 — should_forward_child: normal dep of preprocessing spec
t6_dep_fn(x; __version=v"1.0.0") = (_C(:t6_dep); x * 3)
const t6_dep_was_job = Ref(false)  # verified after preprocessing returns
function t6_preproc(::Preprocessing, dep_job)
	_C(:t6_preproc)
	t6_dep_was_job[] = (dep_job isa Job)
	create_spec(my_double, dep_job; __version=v"1.0.0")
end

# Test 7 — error propagation
t7_bad(x; __version=v"1.0.0")    = error("intentional failure")
t7_parent(x; __version=v"1.0.0") = x + 1

# Test 8 — DAG sharing
t_dag_fn(x; __version=v"1.0.0") = (_C(:t_dag); x + 1)

# Test 9 — fetched dep computed before preprocessing
t_fetched_dep_fn(x; __version=v"1.0.0") = (_C(:t_fetched_dep); x * 5)
const t_fetched_dep_was_value = Ref(false)
function t_fetched_preproc_fn(::Preprocessing, dep)
	_C(:t_fetched_preproc)
	t_fetched_dep_was_value[] = !(dep isa Job)
	create_spec(my_double, dep; __version=v"1.0.0")
end

# Test 10 — Preprocess{false} runs after Preprocess{true}
t_late_early_fn(::Preprocessing, x_job) = (_C(:t_late_early); create_spec(my_double, x_job; __version=v"1.0.0"))
function t_late_late_fn(::Preprocessing, x_job)
	_C(:t_late_late)
	create_spec(my_add, x_job, 10; __version=v"1.0.0")
end

# Test 11 — error in preprocessing
t_bad_preproc_fn(::Preprocessing, x) = error("preproc failure")

# Test 13 — forward_once! stepping (uses t7_bad for ProcessingException; test 12 has no new fns)
t_step_inner(::Preprocessing, x_job) = (_C(:t_step_inner); create_spec(my_double, x_job; __version=v"1.0.0"))
t_step_outer(::Preprocessing, x_job) = (_C(:t_step_outer); create_spec(Preprocess(t_step_inner), x_job))

# Tests 14–15 — on-disk caching
t_cached_fn(x; __version=v"1.0.0")   = (_C(:t_cached); x * 3)
t_compound_fn(x; __version=v"1.0.0") = (_C(:t_compound); CompoundResult(; a=x*2, b=x*3))

# Tests 16–17 — file path types
t_read_tfp(fp; __version=v"1.0.0") = (_C(:t_read_tfp); read(fp.path, String))
t_read_cfp(fp; __version=v"1.0.0") = (_C(:t_read_cfp); read(fp.path, String))


function run_scheduler_tests()
	@testset "Scheduler" begin
		let tmp = mktempdir()
			with_scheduler(Scheduler(; dir=tmp)) do
				_run_scheduler_tests(tmp)
			end
		end
	end
end

function _run_scheduler_tests(dir)
	scheduler = ReproducibleJobs.get_scheduler()


	@testset "No preprocessing" begin
		_CALLS[:t1_f] = 0
		job = create_spec(t1_f, 5; __version=v"1.0.0")

		# forward returns :call immediately — nothing to preprocess
		fwd = forward!(scheduler, job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t1_f) == 0  # compute hasn't run yet

		res = fetch!(scheduler, job)
		@test res == 10
		@test _N(:t1_f) == 1

		fetch!(scheduler, job)  # second fetch uses cache
		@test _N(:t1_f) == 1
	end


	@testset "Single preprocessing step" begin
		_CALLS[:t2_step1] = _CALLS[:t2_double] = 0
		leaf      = create_spec(my_val, 7; __version=v"1.0.0")
		chain_job = create_spec(Preprocess(t2_step1), leaf)

		fwd1 = forward_once!(scheduler, chain_job)
		@test fwd1 isa Job
		@test _N(:t2_step1) == 1 && _N(:t2_double) == 0  # preproc ran; compute did not

		fwd2 = forward!(scheduler, chain_job)
		@test fwd2 isa Job && fwd2.op === :call
		@test _N(:t2_step1) == 1  # cached, not repeated

		res = fetch!(scheduler, chain_job)
		@test res == 14
		@test _N(:t2_double) == 1
	end


	@testset "forward_once vs forward — two-level preprocessing" begin
		_CALLS[:t3_outer] = _CALLS[:t3_inner] = 0
		leaf = create_spec(my_val, 3; __version=v"1.0.0")
		job  = create_spec(Preprocess(t3_outer), leaf)

		# one step: outer runs, inner does not
		fwd1 = forward_once!(scheduler, job)
		@test fwd1 isa Job && fwd1.op === :forward
		@test _N(:t3_outer) == 1 && _N(:t3_inner) == 0

		# full forward: both levels run
		fwd2 = forward!(scheduler, job)
		@test fwd2 isa Job && fwd2.op === :call
		@test _N(:t3_outer) == 1 && _N(:t3_inner) == 1  # outer not repeated

		@test fetch!(scheduler, job) == 6
	end


	@testset "Prefetched dep in preprocessing output" begin
		_CALLS[:t4_get_len] = _CALLS[:t4_use_len] = 0
		data_job = create_spec(my_val, [1, 2, 3, 4]; __version=v"1.0.0")
		job      = create_spec(Preprocess(t4_make_len_spec), data_job)

		@test fetch!(scheduler, job) == 40   # use_len(length([1,2,3,4])) = 4*10
		@test _N(:t4_get_len) == 1 && _N(:t4_use_len) == 1
	end


	@testset "should_forward_child — preprocessing dep of normal spec is forwarded" begin
		_CALLS[:t5_preproc] = _CALLS[:t5_double] = 0
		leaf        = create_spec(my_val, 5; __version=v"1.0.0")
		preproc_job = create_spec(Preprocess(t5_preproc), leaf)
		parent_job  = create_spec(my_add, preproc_job, 1; __version=v"1.0.0")

		# forwarding the parent triggers forwarding of the preprocessing dep
		fwd = forward!(scheduler, parent_job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t5_preproc) == 1 && _N(:t5_double) == 0

		@test fetch!(scheduler, parent_job) == 11   # my_add(t5_double(5), 1) = 11
		@test _N(:t5_double) == 1
	end


	@testset "should_forward_child — normal dep of preprocessing spec is not forwarded" begin
		_CALLS[:t6_preproc] = _CALLS[:t6_dep] = 0
		t6_dep_was_job[] = false
		dep_job = create_spec(t6_dep_fn, 4; __version=v"1.0.0")
		job     = create_spec(Preprocess(t6_preproc), dep_job)

		forward!(scheduler, job)
		@test _N(:t6_preproc) == 1
		@test t6_dep_was_job[]      # preprocessing received dep as Job, not a value
		@test _N(:t6_dep) == 0       # dep NOT computed during forward

		@test fetch!(scheduler, job) == 24   # my_double(t6_dep_fn(4)) = 24
		@test _N(:t6_dep) == 1
	end


	@testset "Error propagation" begin
		dep_job    = create_spec(t7_bad, 0; __version=v"1.0.0")
		parent_job = create_spec(t7_parent, dep_job; __version=v"1.0.0")

		@test_throws "intentional failure" fetch!(scheduler, parent_job)
	end


	@testset "DAG sharing — shared dep computed once" begin
		_CALLS[:t_dag] = 0
		leaf    = create_spec(my_val, 100; __version=v"1.0.0")
		dep     = create_spec(t_dag_fn, leaf; __version=v"1.0.0")
		parent1 = create_spec(my_add, dep, 0; __version=v"1.0.0")
		parent2 = create_spec(my_add, dep, 1000; __version=v"1.0.0")

		r1 = fetch!(scheduler, parent1)
		r2 = fetch!(scheduler, parent2)
		@test r1 == 101    # t_dag_fn(100) + 0 = 101
		@test r2 == 1101   # t_dag_fn(100) + 1000 = 1101
		@test _N(:t_dag) == 1   # shared dep computed only once
	end


	@testset "fetched dep is computed before preprocessing runs" begin
		_CALLS[:t_fetched_dep] = _CALLS[:t_fetched_preproc] = 0
		t_fetched_dep_was_value[] = false
		leaf = create_spec(my_val, 11; __version=v"1.0.0")
		dep  = create_spec(t_fetched_dep_fn, leaf; __version=v"1.0.0")
		job  = create_spec(Preprocess(t_fetched_preproc_fn), fetched(dep))

		# During forwarding, the fetched dep is computed; preprocessing receives its VALUE
		fwd = forward!(scheduler, job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t_fetched_dep) == 1
		@test _N(:t_fetched_preproc) == 1
		@test t_fetched_dep_was_value[]   # received a value, not a Job

		result = fetch!(scheduler, job)
		@test result == 2 * (11 * 5)   # my_double(t_fetched_dep_fn(11)) = 2*55 = 110
	end


	@testset "Preprocess{false} runs after Preprocess{true}" begin
		_CALLS[:t_late_early] = _CALLS[:t_late_late] = 0
		leaf      = create_spec(my_val, 30; __version=v"1.0.0")
		early_job = create_spec(Preprocess(t_late_early_fn), leaf)          # early: doubles x
		job       = create_spec(Preprocess{false}(t_late_late_fn), early_job)  # late: adds 10

		fwd = forward!(scheduler, job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t_late_early) == 1 && _N(:t_late_late) == 1

		result = fetch!(scheduler, job)
		@test result == my_double(30) + 10   # 60 + 10 = 70
	end


	@testset "Error in preprocessing" begin
		dep_job = create_spec(my_val, 200; __version=v"1.0.0")
		job     = create_spec(Preprocess(t_bad_preproc_fn), dep_job)
		@test_throws "preproc failure" fetch!(scheduler, job)
	end


	@testset "ProcessingException structure" begin
		dep_job    = create_spec(t7_bad, 99; __version=v"1.0.0")
		parent_job = create_spec(t7_parent, dep_job; __version=v"1.0.0")
		exc = nothing
		try
			fetch!(scheduler, parent_job)
		catch e
			exc = e
		end
		@test exc isa ProcessingException
		@test exc.inner isa ErrorException
		@test occursin("intentional failure", exc.inner.msg)
		@test length(exc.stack) >= 1
	end


	@testset "forward_once! stepping" begin
		_CALLS[:t_step_inner] = _CALLS[:t_step_outer] = 0
		leaf = create_spec(my_val, 42; __version=v"1.0.0")
		job  = create_spec(Preprocess(t_step_outer), leaf)

		# step 1: outer runs, inner does not
		fwd1 = forward_once!(scheduler, job)
		@test fwd1 isa Job && fwd1.op === :forward
		@test _N(:t_step_outer) == 1 && _N(:t_step_inner) == 0

		# advance to :call; outer is not repeated
		fwd_final = forward!(scheduler, job)
		@test fwd_final isa Job && fwd_final.op === :call
		@test _N(:t_step_outer) == 1 && _N(:t_step_inner) == 1

		# forward_once on the fully-forwarded result is idempotent
		fwd_again = forward_once!(scheduler, fwd_final)
		@test fwd_again === fwd_final

		@test fetch!(scheduler, job) == 84   # my_double(42) = 84
	end


	@testset "Cached on-disk — second scheduler finds result" begin
		_CALLS[:t_cached] = 0
		inner = create_spec(t_cached_fn, 7; __version=v"1.0.0")
		job   = cached(inner)

		r1 = fetch!(scheduler, job)
		@test r1 == 21       # 7 * 3
		@test _N(:t_cached) == 1

		# A fresh scheduler with the same cache dir should hit the on-disk result
		with_scheduler(Scheduler(; dir=dir)) do
			sched2 = ReproducibleJobs.get_scheduler()
			r2 = fetch!(sched2, job)
			@test r2 == 21
			@test _N(:t_cached) == 1   # not recomputed
		end
	end


	@testset "Cached CompoundResult sub-results" begin
		_CALLS[:t_compound] = 0
		inner = create_spec(t_compound_fn, 5; __version=v"1.0.0")
		sub_a = cached(inner, "a")
		sub_b = cached(inner, "b")

		@test fetch!(scheduler, sub_a) == 10   # 5*2
		@test fetch!(scheduler, sub_b) == 15   # 5*3
		@test _N(:t_compound) == 1   # compound fn called once for both sub-results
	end


	@testset "TimestampedFilePath — mtime change creates distinct spec" begin
		_CALLS[:t_read_tfp] = 0
		fp  = joinpath(dir, "ts_test.txt")
		write(fp, "version1")
		ts1  = TimestampedFilePath(fp)
		job1 = create_spec(t_read_tfp, ts1; __version=v"1.0.0")
		@test fetch!(scheduler, job1) == "version1"
		@test _N(:t_read_tfp) == 1

		# Artificially different timestamp → different spec → must recompute
		ts2  = TimestampedFilePath(ts1.path, ts1.timestamp + 1.0)
		job2 = create_spec(t_read_tfp, ts2; __version=v"1.0.0")
		@test job2 !== job1
		@test fetch!(scheduler, job2) == "version1"   # same file, different spec
		@test _N(:t_read_tfp) == 2
	end


	@testset "ChecksummedFilePath — same checksum deduplicated, different checksum distinct" begin
		_CALLS[:t_read_cfp] = 0
		fp   = joinpath(dir, "cfp_test.txt")
		write(fp, "stable content")
		cfp1 = ChecksummedFilePath(fp)
		job1 = create_spec(t_read_cfp, cfp1; __version=v"1.0.0")
		@test fetch!(scheduler, job1) == "stable content"
		@test _N(:t_read_cfp) == 1

		# Same checksum, different timestamp → same spec (hash is checksum-only)
		cfp2 = ChecksummedFilePath(cfp1.path, cfp1.timestamp + 100.0, cfp1.checksum)
		@test isequal(cfp1, cfp2)   # isequal by checksum
		job2 = create_spec(t_read_cfp, cfp2; __version=v"1.0.0")
		@test job2 === job1   # deduplicated to the same Job
		@test _N(:t_read_cfp) == 1   # not recomputed

		# Different content → different checksum → different spec → must recompute
		write(fp, "new content")
		cfp3 = ChecksummedFilePath(fp)
		@test !isequal(cfp1, cfp3)
		job3 = create_spec(t_read_cfp, cfp3; __version=v"1.0.0")
		@test job3 !== job1
		@test fetch!(scheduler, job3) == "new content"
		@test _N(:t_read_cfp) == 2
	end
end
