# These tests were generated by Claude and improved slightly.
# More work and thought is needed, but this is better than nothing.

using Test
using ReproducibleJobs
using ReproducibleJobs: create_spec, with_scheduler, Preprocessing
import ReproducibleJobs: fetch_new!, forward_new!, forward_once_new!


# All test functions must be at module scope (named, non-closure) so the
# scheduler can hash them reliably.

const _CALLS = Dict{Symbol,Int}()
_N(s::Symbol) = get(_CALLS, s, 0)           # read count
_C(s::Symbol) = (_CALLS[s] = _N(s) + 1)    # increment count

# Shared compute primitives (no counting)
my_double(x; __version=v"1.0.0") = 2x
my_add(a, b; __version=v"1.0.0") = a + b
my_val(x; __version=v"1.0.0") = x

# Test 1
t1_f(x; __version=v"1.0.0") = (_C(:t1_f); 2x)

# Test 2 — single preprocessing step
t2_double(x; __version=v"1.0.0")       = (_C(:t2_double); 2x)
t2_step1(::Preprocessing, x_job)       = (_C(:t2_step1); create_spec(t2_double, x_job; __version=v"1.0.0"))

# Test 3 — two-level preprocessing
t3_inner(::Preprocessing, x_job) = (_C(:t3_inner); create_spec(my_double, x_job; __version=v"1.0.0"))
t3_outer(::Preprocessing, x_job) = (_C(:t3_outer); create_spec(Preprocess(t3_inner), x_job))

# Test 4 — prefetched dep in preprocessing output
t4_get_len(x; __version=v"1.0.0") = (_C(:t4_get_len); length(x))
t4_use_len(n; __version=v"1.0.0") = (_C(:t4_use_len); n * 10)
function t4_make_len_spec(::Preprocessing, data_job)
	len_spec = create_spec(t4_get_len, data_job; __version=v"1.0.0")
	create_spec(t4_use_len, prefetched(len_spec); __version=v"1.0.0")
end

# Test 5 — should_forward_child: preprocessing dep of normal spec
t5_double(x; __version=v"1.0.0")    = (_C(:t5_double); 2x)
t5_preproc(::Preprocessing, x_job)  = (_C(:t5_preproc); create_spec(t5_double, x_job; __version=v"1.0.0"))

# Test 6 — should_forward_child: normal dep of preprocessing spec
t6_dep_fn(x; __version=v"1.0.0") = (_C(:t6_dep); x * 3)
const t6_dep_was_job = Ref(false)  # verified after preprocessing returns
function t6_preproc(::Preprocessing, dep_job)
	_C(:t6_preproc)
	t6_dep_was_job[] = (dep_job isa Job)
	create_spec(my_double, dep_job; __version=v"1.0.0")
end

# Test 7 — error propagation
t7_bad(x; __version=v"1.0.0")    = error("intentional failure")
t7_parent(x; __version=v"1.0.0") = x + 1


function run_scheduler_tests()
	@testset "Scheduler" begin
		let tmp = mktempdir()
			with_scheduler(Scheduler(; dir=tmp)) do
				_run_scheduler_tests()
			end
		end
	end
end

function _run_scheduler_tests()
	scheduler = ReproducibleJobs.get_scheduler()


	@testset "No preprocessing" begin
		_CALLS[:t1_f] = 0
		job = create_spec(t1_f, 5; __version=v"1.0.0")

		# forward returns :call immediately — nothing to preprocess
		fwd = forward_new!(scheduler, job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t1_f) == 0  # compute hasn't run yet

		res = fetch_new!(scheduler, job)
		@test res == 10
		@test _N(:t1_f) == 1

		fetch_new!(scheduler, job)  # second fetch uses cache
		@test _N(:t1_f) == 1
	end


	@testset "Single preprocessing step" begin
		_CALLS[:t2_step1] = _CALLS[:t2_double] = 0
		leaf      = create_spec(my_val, 7; __version=v"1.0.0")
		chain_job = create_spec(Preprocess(t2_step1), leaf)

		fwd1 = forward_once_new!(scheduler, chain_job)
		@test fwd1 isa Job
		@test _N(:t2_step1) == 1 && _N(:t2_double) == 0  # preproc ran; compute did not

		fwd2 = forward_new!(scheduler, chain_job)
		@test fwd2 isa Job && fwd2.op === :call
		@test _N(:t2_step1) == 1  # cached, not repeated

		res = fetch_new!(scheduler, chain_job)
		@test res == 14
		@test _N(:t2_double) == 1
	end


	@testset "forward_once vs forward — two-level preprocessing" begin
		_CALLS[:t3_outer] = _CALLS[:t3_inner] = 0
		leaf = create_spec(my_val, 3; __version=v"1.0.0")
		job  = create_spec(Preprocess(t3_outer), leaf)

		# one step: outer runs, inner does not
		fwd1 = forward_once_new!(scheduler, job)
		@test fwd1 isa Job && fwd1.op === :forward
		@test _N(:t3_outer) == 1 && _N(:t3_inner) == 0

		# full forward: both levels run
		fwd2 = forward_new!(scheduler, job)
		@test fwd2 isa Job && fwd2.op === :call
		@test _N(:t3_outer) == 1 && _N(:t3_inner) == 1  # outer not repeated

		@test fetch_new!(scheduler, job) == 6
	end


	@testset "Prefetched dep in preprocessing output" begin
		_CALLS[:t4_get_len] = _CALLS[:t4_use_len] = 0
		data_job = create_spec(my_val, [1, 2, 3, 4]; __version=v"1.0.0")
		job      = create_spec(Preprocess(t4_make_len_spec), data_job)

		@test fetch_new!(scheduler, job) == 40   # use_len(length([1,2,3,4])) = 4*10
		@test _N(:t4_get_len) == 1 && _N(:t4_use_len) == 1
	end


	@testset "should_forward_child — preprocessing dep of normal spec is forwarded" begin
		_CALLS[:t5_preproc] = _CALLS[:t5_double] = 0
		leaf        = create_spec(my_val, 5; __version=v"1.0.0")
		preproc_job = create_spec(Preprocess(t5_preproc), leaf)
		parent_job  = create_spec(my_add, preproc_job, 1; __version=v"1.0.0")

		# forwarding the parent triggers forwarding of the preprocessing dep
		fwd = forward_new!(scheduler, parent_job)
		@test fwd isa Job && fwd.op === :call
		@test _N(:t5_preproc) == 1 && _N(:t5_double) == 0

		@test fetch_new!(scheduler, parent_job) == 11   # my_add(t5_double(5), 1) = 11
		@test _N(:t5_double) == 1
	end


	@testset "should_forward_child — normal dep of preprocessing spec is not forwarded" begin
		_CALLS[:t6_preproc] = _CALLS[:t6_dep] = 0
		t6_dep_was_job[] = false
		dep_job = create_spec(t6_dep_fn, 4; __version=v"1.0.0")
		job     = create_spec(Preprocess(t6_preproc), dep_job)

		forward_new!(scheduler, job)
		@test _N(:t6_preproc) == 1
		@test t6_dep_was_job[]      # preprocessing received dep as Job, not a value
		@test _N(:t6_dep) == 0       # dep NOT computed during forward

		@test fetch_new!(scheduler, job) == 24   # my_double(t6_dep_fn(4)) = 24
		@test _N(:t6_dep) == 1
	end


	@testset "Error propagation" begin
		dep_job    = create_spec(t7_bad, 0; __version=v"1.0.0")
		parent_job = create_spec(t7_parent, dep_job; __version=v"1.0.0")

		@test_throws "intentional failure" fetch_new!(scheduler, parent_job)
	end
end
