name = "CacheBySpec"
uuid = "2ffa5f23-53ba-4141-98f3-a176c30fe328"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.1.0"

[deps]

[compat]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
