name = "CacheBySpec"
uuid = "2ffa5f23-53ba-4141-98f3-a176c30fe328"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
StableHashTraits = "c5dd0088-6c3f-4803-b00e-f31a60c170fa"

[compat]
StableHashTraits = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
